// Code generated by 'yaegi extract github.com/cherry-game/cherry-hotfix/test/model'. DO NOT EDIT.

package symbols

import (
	"github.com/cherry-game/cherry-hotfix/test/model"
	"reflect"
)

func init() {
	Symbols["github.com/cherry-game/cherry-hotfix/test/model/model"] = map[string]reflect.Value{
		// type definitions
		"Foo": reflect.ValueOf((*model.Foo)(nil)),
	}
}
